title: Ferdinand Beltsazar # Ferdinand Beltsazar
logo: [My image](Ferdi0602/ferdinandbeltsazar.github.com/repository/img/logo.jpg)
description: > Sedang Mengikuti Kegiatan Kampus Merdeka
  Studi Independent Bersertifikat
  <br><br>
  Kuliah di Universitas Pamulang Jurusan Matematika
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
