title: Ferdinand Beltsazar # Ferdinand Beltsazar
logo: WhatsApp Image 2022-04-22 at 13.53.32.jpeg
description: > Sedang Mengikuti Kegiatan Kampus Merdeka
  Studi Independent Bersertifikat
  <br><br>
  Kuliah di Universitas Pamulang Jurusan Matematika
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
